services:
  # Backend API
  - type: web
    name: blood-donation-backend
    runtime: node
    region: singapore
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
\
  # Frontend Static Site
  - type: web
    name: blood-donation-frontend
    runtime: static
    region: singapore
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist

    routes:
      - type: rewrite
        source: /*
        destination: /index.html
