services:
  # Backend API
  - type: web
    name: blood-donation-backend
    runtime: node
    region: singapore
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        value: mongodb+srv://chirag562:ONlt2AkocdRY2jdu@aviothic01.e67ncgo.mongodb.net/?retryWrites=true&w=majority&appName=aviothic01
      - key: JWT_SECRET
        value: my_very_strong_and_secure_jwt_secret_key_12345

  # Frontend Static Site
  - type: web
    name: blood-donation-frontend
    runtime: static
    region: singapore
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html